// Design tokens from stitch_ui/.../electric_glass_gastro/DESIGN.md
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#131317",
        surface: "#131317",
        "surface-bright": "#39393d",
        "surface-container-lowest": "#0e0e12",
        "surface-container-low": "#1b1b1f",
        "surface-container": "#1f1f23",
        "surface-container-high": "#2a292e",
        "surface-container-highest": "#353439",
        "on-surface": "#e4e1e7",
        "on-surface-variant": "#e2bdc3",
        outline: "#aa888e",
        "outline-variant": "#5a4045",
        primary: "#ffb1c1",
        "primary-container": "#ff4c85",
        "primary-fixed": "#ffd9df",
        "on-primary-fixed": "#3f0017",
        secondary: "#cabeff",
        "secondary-container": "#4816cb",
        "secondary-fixed": "#e6deff",
        tertiary: "#a2d801",
        "tertiary-container": "#759e00",
        "tertiary-fixed": "#bdf532",
        amber: "#ffb800",
        error: "#ffb4ab",
        "error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        margin: "1rem",
        "margin-desktop": "3rem",
      },
      fontFamily: {
        display: ["Space Grotesk", "Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-xl-mobile": ["36px", { lineHeight: "40px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "30px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "26px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em" }],
        "body-md": ["14px", { lineHeight: "20px" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em" }],
        "label-lg": ["14px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "12px", letterSpacing: "0.05em", fontWeight: "700" }],
      },
    },
  },
};
